### ISSUE TITLE
Lazy plugin code snippet for plugin

### ISSUE THREAD

**Issue by b9Joker108** [fowlie/open-github-repo#1]
Hi 

Sorry for being such a noob. I could could really do with being spoon-fed the Lazy plugin code snippet for your Neovim plugin, and please add it to the repo README.md for others!

Cheers
Beauford

**Comment by fowlie** [comment]
No problem. :) A good readme file is always nice. I'll add it when I get back to my computer.

**Comment by b9Joker108** [comment]
Thank you so much for that: excellent!
